### ISSUE TITLE
Cannot build on Ubuntu 18.04

### ISSUE THREAD

**Issue by iSnow** [QuantisNetwork/Quantis-public#3]
Installed gcc, gpp, libboost-dev 1.65, libssl-dev and tried building with `make -j4 -f makefile.unix RELEASE`

Build failed with lots of errors like: 

   bignum.h: In function ‘bool operator==(const CBigNum&, const CBigNum&)’:
bignum.h:715:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator==(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) == 0); }
